### ISSUE TITLE
Fix python environment setup

### ISSUE THREAD

**Issue by mkienenb** [CorningTopTier/expense-report#9]
## User story
We want to make setting up the environment easy between collaborators.

# Problem solution
Our first pass at setting up a shared python environment was the wrong approach.
Instead we should be using a requirements.txt file and not committing the venv files.

**Comment by CorningTopTier** [comment]
Do I need to change this for myself also?

**Comment by mkienenb** [comment]
Yes, you should change it for yourself as well
